# Generated by Django 6.0.4 on 2026-04-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('DEAN', 'Dean'), ('TENURED PROFESSOR', 'Tenured Professor'), ('ADJUNCT PROFESSOR', 'Adjunct Professor'), ('ADMIN STAFF', 'Administrative Staff'), ('MAINTENANCE', 'Maintenance Staff'), ('WORK STUDY', 'Student Worker')], max_length=25),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role_ended',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
